name: .NET 8 Deploy

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      #shen/MockHttp  拿仓库的最后名称写入环境变量
      - name: Get PROJECT_NAME
        run: |
          echo "PROJECT_NAME = ${GITHUB_REPOSITORY##*/}"
          echo "PROJECT_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV


      #判断是否写入环境变量
      - name: Safety check
        run: |
          if [ -z "${{ env.PROJECT_NAME }}" ]; then
          echo "PROJECT_NAME is empty, abort deploy"
          exit 1
          fi

      #打印环境变量
      - name: Print PROJECT_NAME (expression)
        run: |
          echo "PROJECT_NAME=${{ env.PROJECT_NAME }}"

      #发布到publish
      - name: Publish WebApi
        run: |
          dotnet publish -r linux-x64 -c Release -o ./publish -p:DebugType=None -p:DebugSymbols=false

      #同步到服务器  仓库要配置密钥  服务器安装tar
      - name: Deploy to Server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "publish/*"
          target: "/Sxx/Service/${{ env.PROJECT_NAME }}"
          strip_components: 1

      #重启服务
      - name: Restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart Sxx.${{ env.PROJECT_NAME }}.service
